<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>אתר עלה לcloud אבל הוא לא מגיב לחלק מהresponse</title>
    <link>https://forums.pythonic.guru/t/cloud-response/8397</link>
    <description>אחרי שעות האתר עלה בצורה תקינה לheroku 

למרות זאת, חלק מהפעולות עובדות בצורה תקינה וחלק מעבירות הודעה -
&quot; Internal Server Error&quot; - ההודעה מוחזרת כתגובה פעולת הלחיצה. מטרת הלחיצה מחזירה response ומורידה קובץ csv למחשב.

חיפשתי באינטרנט את מקור הבעיה, וכמובן שעברתי פעמים רבות להשוואת בין הפעולה שכן עובדות(מורידות את הקובץ) והפעולות שלא מורידות... (בהרצה דרך שרת מקומי הכל עובד תקין )

אשמח לעזרה חברים</description>
    <language>he</language>
    <lastBuildDate>Sat, 24 Oct 2020 21:50:20 +0000</lastBuildDate>
    <category>שבוע 12</category>
    <atom:link href="https://forums.pythonic.guru/t/cloud-response/8397.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>אתר עלה לcloud אבל הוא לא מגיב לחלק מהresponse</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>בגדול Internal Server Error אומר שה־Flask שלך קרס כשהוא ניסה להגיש את הבקשה.<br>
כדי לטפל בזה צריך להסתכל על הלוגים ב־Heroku ולראות מה הודעת השגיאה שחזרה.</p>
          <p><a href="https://forums.pythonic.guru/t/cloud-response/8397/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/cloud-response/8397/2</link>
        <pubDate>Sat, 24 Oct 2020 21:50:20 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8397-2</guid>
        <source url="https://forums.pythonic.guru/t/cloud-response/8397.rss">אתר עלה לcloud אבל הוא לא מגיב לחלק מהresponse</source>
      </item>
      <item>
        <title>אתר עלה לcloud אבל הוא לא מגיב לחלק מהresponse</title>
        <dc:creator><![CDATA[ofirhaimofir96]]></dc:creator>
        <description><![CDATA[
            <p>אחרי שעות האתר עלה בצורה תקינה לheroku</p>
<p>למרות זאת, חלק מהפעולות עובדות בצורה תקינה וחלק מעבירות הודעה -<br>
" Internal Server Error" - ההודעה מוחזרת כתגובה פעולת הלחיצה. מטרת הלחיצה מחזירה response ומורידה קובץ csv למחשב.</p>
<p>חיפשתי באינטרנט את מקור הבעיה, וכמובן שעברתי פעמים רבות להשוואת בין הפעולה שכן עובדות(מורידות את הקובץ) והפעולות שלא מורידות… (בהרצה דרך שרת מקומי הכל עובד תקין )</p>
<p>אשמח לעזרה חברים</p>
          <p><a href="https://forums.pythonic.guru/t/cloud-response/8397/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/cloud-response/8397/1</link>
        <pubDate>Sat, 24 Oct 2020 21:37:26 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8397-1</guid>
        <source url="https://forums.pythonic.guru/t/cloud-response/8397.rss">אתר עלה לcloud אבל הוא לא מגיב לחלק מהresponse</source>
      </item>
  </channel>
</rss>
