<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>תקלה מוזרה ב - Jupyter</title>
    <link>https://forums.pythonic.guru/t/jupyter/5721</link>
    <description>היי,

במחברת 2 (מילונים) שבוע 4 - נדרש באחת מהשאלות לפתוח קובץ.
כשאני מנסה לפתוח את הקובץ אני מקבל את השגיאה הבאה:

![image|690x263](upload://2fDQre1FlqLO6kjvEgdVosGZnYY.png) 

מישהו יכול לעזור איך לפתור את הבעייה?
יש לי טעות בקוד?

תודה מראש לעוזרים!</description>
    <language>he</language>
    <lastBuildDate>Fri, 01 May 2020 17:28:36 +0000</lastBuildDate>
    <category>מחוץ לקטגוריה</category>
    <atom:link href="https://forums.pythonic.guru/t/jupyter/5721.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>תקלה מוזרה ב - Jupyter</title>
        <dc:creator><![CDATA[Almog]]></dc:creator>
        <description><![CDATA[
            <p>הקובץ הזה ארוך וכבד מדי להדפסה ותצוגה בג’ופיטר, ולכן השגיאה הזו קורית (לכולם אגב, אם תריץ חיפוש זריז בפורום תראה שהשאלה הזאת עלתה כבר מספר פעמים).<br>
ממליצה כאלטרנטיבה להדפיס רק חלק קטן כדי לבדוק שאתה בכיוון הנכון <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/jupyter/5721/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/jupyter/5721/2</link>
        <pubDate>Fri, 01 May 2020 17:28:36 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-5721-2</guid>
        <source url="https://forums.pythonic.guru/t/jupyter/5721.rss">תקלה מוזרה ב - Jupyter</source>
      </item>
      <item>
        <title>תקלה מוזרה ב - Jupyter</title>
        <dc:creator><![CDATA[EliranRefaely]]></dc:creator>
        <description><![CDATA[
            <p>היי,</p>
<p>במחברת 2 (מילונים) שבוע 4 - נדרש באחת מהשאלות לפתוח קובץ.<br>
כשאני מנסה לפתוח את הקובץ אני מקבל את השגיאה הבאה:</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/0/0fc9052a1981994b6d387a425461d54be8ef3ad8.png" data-download-href="https://forums.pythonic.guru/uploads/default/0fc9052a1981994b6d387a425461d54be8ef3ad8" title="image"><img src="https://forums.pythonic.guru/uploads/default/original/2X/0/0fc9052a1981994b6d387a425461d54be8ef3ad8.png" alt="image" data-base62-sha1="2fDQre1FlqLO6kjvEgdVosGZnYY" width="690" height="263" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/0/0fc9052a1981994b6d387a425461d54be8ef3ad8_2_10x10.png"></a></div><p></p>
<p>מישהו יכול לעזור איך לפתור את הבעייה?<br>
יש לי טעות בקוד?</p>
<p>תודה מראש לעוזרים!</p>
          <p><a href="https://forums.pythonic.guru/t/jupyter/5721/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/jupyter/5721/1</link>
        <pubDate>Fri, 01 May 2020 17:23:33 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-5721-1</guid>
        <source url="https://forums.pythonic.guru/t/jupyter/5721.rss">תקלה מוזרה ב - Jupyter</source>
      </item>
  </channel>
</rss>
