<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>שגיאה - Task was destroyed but it is pending!</title>
    <link>https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065</link>
    <description>היי,

לא הצלחתי למצוא תשובות בעצמי.
בטסט האחרון של test_zodiac אני נתקל בבעיה הבאה:

![Screen Shot 2021-02-08 at 9.59.27|690x109](upload://ayKNwyVd9GIqFBuNpwnDqriUWcs.png) 

יש לכם מושג איך להתמודד?

תודה!</description>
    <language>he</language>
    <lastBuildDate>Sat, 13 Feb 2021 09:42:12 +0000</lastBuildDate>
    <category>שבוע 16</category>
    <atom:link href="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>שגיאה - Task was destroyed but it is pending!</title>
        <dc:creator><![CDATA[eliory09]]></dc:creator>
        <description><![CDATA[
            <p>תודה רבה! חלק מהבעיות אכן הסתדרו כששינמכתי <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/5">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/5</link>
        <pubDate>Sat, 13 Feb 2021 09:42:12 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9065-5</guid>
        <source url="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065.rss">שגיאה - Task was destroyed but it is pending!</source>
      </item>
      <item>
        <title>שגיאה - Task was destroyed but it is pending!</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>תעדכן כך שבמחשב שלך יהיה את מה שנמצא על השרת המרוחק, תקח משם את קובץ requirementst.txt ותתקין את החבילות מחדש.<br>
יש באג ב־pytest-asyncio, אז שינמכנו אותו שלשום וכרגע זה עובד</p>
<ol>
<li><code>git fetch upstream</code></li>
<li><code>git checkout upstream:develop -- requirements.txt</code></li>
<li><code>pip install -U -r requirements.txt</code></li>
</ol>
          <p><a href="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/4">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/4</link>
        <pubDate>Mon, 08 Feb 2021 17:20:25 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9065-4</guid>
        <source url="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065.rss">שגיאה - Task was destroyed but it is pending!</source>
      </item>
      <item>
        <title>שגיאה - Task was destroyed but it is pending!</title>
        <dc:creator><![CDATA[eliory09]]></dc:creator>
        <description><![CDATA[
            <p>תודה גוני. בדקתי בעצמי וראיתי שבאמת מדובר בשגיאה שקשורה ל-Event loop.<br>
בכל מקרה, כרגע הטסטים לא עוברים אצלי מקומית, אבל עברו ב-PR.<br>
אני אנסה להתקין את הסביבה מחדש ולראות אם משהו משתנה <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
<p>ובכל זאת, אם יש למישהו מושג מה עושים (כי אני עוד חדש בכל הנושא של async), אשמח לשמוע עוד טיפים!</p>
          <p><a href="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/3</link>
        <pubDate>Mon, 08 Feb 2021 16:42:06 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9065-3</guid>
        <source url="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065.rss">שגיאה - Task was destroyed but it is pending!</source>
      </item>
      <item>
        <title>שגיאה - Task was destroyed but it is pending!</title>
        <dc:creator><![CDATA[gonny]]></dc:creator>
        <description><![CDATA[
            <p>נתקלתי בזה אתמול. התאוריה שלי כרגע שיש כנראה זליגה של session מבדיקה אחרת. אם תעשה comment out לכל הקובץ של test_agenda_route.py אתה תראה שיופיעו שגיאות בקבצים אחרים שעוברים תקין כרגע.</p>
<p>בנוסף, אם תוסיף עוד פונקציה אחרי הפונקציה שנכשלה, אתה תראה שהפונקציה הנוכחית עוברת והחדשה תיכשל, כך שזה לא קשור אליה.</p>
<p>משהו שים אמר לי לשים לב שעזר לPR לא להיכשל בבדיקה הזאת, זה לוודא ש pytest-asyncio&lt;0.14.0 מוגדר ככה.</p>
          <p><a href="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/2</link>
        <pubDate>Mon, 08 Feb 2021 08:56:42 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9065-2</guid>
        <source url="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065.rss">שגיאה - Task was destroyed but it is pending!</source>
      </item>
      <item>
        <title>שגיאה - Task was destroyed but it is pending!</title>
        <dc:creator><![CDATA[eliory09]]></dc:creator>
        <description><![CDATA[
            <p>היי,</p>
<p>לא הצלחתי למצוא תשובות בעצמי.<br>
בטסט האחרון של test_zodiac אני נתקל בבעיה הבאה:</p>
<p></p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/4/4a037c16aec22985cc9f93d40959036dc6c0efec.png" data-download-href="https://forums.pythonic.guru/uploads/default/4a037c16aec22985cc9f93d40959036dc6c0efec" title="Screen Shot 2021-02-08 at 9.59.27"><img src="https://forums.pythonic.guru/uploads/default/optimized/2X/4/4a037c16aec22985cc9f93d40959036dc6c0efec_2_690x109.png" alt="Screen Shot 2021-02-08 at 9.59.27" data-base62-sha1="ayKNwyVd9GIqFBuNpwnDqriUWcs" width="690" height="109" srcset="https://forums.pythonic.guru/uploads/default/optimized/2X/4/4a037c16aec22985cc9f93d40959036dc6c0efec_2_690x109.png, https://forums.pythonic.guru/uploads/default/optimized/2X/4/4a037c16aec22985cc9f93d40959036dc6c0efec_2_1035x163.png 1.5x, https://forums.pythonic.guru/uploads/default/optimized/2X/4/4a037c16aec22985cc9f93d40959036dc6c0efec_2_1380x218.png 2x" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/4/4a037c16aec22985cc9f93d40959036dc6c0efec_2_10x10.png"></a></div><p></p>
<p>יש לכם מושג איך להתמודד?</p>
<p>תודה!</p>
          <p><a href="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065/1</link>
        <pubDate>Mon, 08 Feb 2021 08:25:07 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-9065-1</guid>
        <source url="https://forums.pythonic.guru/t/task-was-destroyed-but-it-is-pending/9065.rss">שגיאה - Task was destroyed but it is pending!</source>
      </item>
  </channel>
</rss>
