<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Group_by- בדיקות אוטומטיות</title>
    <link>https://forums.pythonic.guru/t/group-by/6842</link>
    <description>היי,
אני מקבל את השגיאה הבאה:
![image|690x122](upload://lIVsv6ilhYsLJ8ctOeVndtfHjGo.png) 
אני משער שזה קורה בגלל שאני משתמש ב-set בפונקציה (על מנת למנוע כפילויות).
מישהו יודע האם זאת הבעיה? ואם לא אז מה השגיאה אומרת?</description>
    <language>he</language>
    <lastBuildDate>Mon, 01 Jun 2020 10:13:26 +0000</lastBuildDate>
    <category>מחוץ לקטגוריה</category>
    <atom:link href="https://forums.pythonic.guru/t/group-by/6842.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Group_by- בדיקות אוטומטיות</title>
        <dc:creator><![CDATA[yuval.cagan]]></dc:creator>
        <description><![CDATA[
            <p>ספציפית במקרה הזה ההבדל בין התשובות שלך לתשובות שהבודק האוטומטי מצפה אליהן הוא סדר המילים בתוך הרשימה. יש לזה פתרון פשוט.</p>
          <p><a href="https://forums.pythonic.guru/t/group-by/6842/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/group-by/6842/2</link>
        <pubDate>Mon, 01 Jun 2020 10:13:26 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6842-2</guid>
        <source url="https://forums.pythonic.guru/t/group-by/6842.rss">Group_by- בדיקות אוטומטיות</source>
      </item>
      <item>
        <title>Group_by- בדיקות אוטומטיות</title>
        <dc:creator><![CDATA[tamirduv]]></dc:creator>
        <description><![CDATA[
            <p>היי,<br>
אני מקבל את השגיאה הבאה:<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/9/9841c1d93718dd442f9a22b7a6b5a82440f86548.png" data-download-href="https://forums.pythonic.guru/uploads/default/9841c1d93718dd442f9a22b7a6b5a82440f86548" title="image"><img src="https://forums.pythonic.guru/uploads/default/optimized/2X/9/9841c1d93718dd442f9a22b7a6b5a82440f86548_2_690x122.png" alt="image" data-base62-sha1="lIVsv6ilhYsLJ8ctOeVndtfHjGo" width="690" height="122" srcset="https://forums.pythonic.guru/uploads/default/optimized/2X/9/9841c1d93718dd442f9a22b7a6b5a82440f86548_2_690x122.png, https://forums.pythonic.guru/uploads/default/original/2X/9/9841c1d93718dd442f9a22b7a6b5a82440f86548.png 1.5x, https://forums.pythonic.guru/uploads/default/original/2X/9/9841c1d93718dd442f9a22b7a6b5a82440f86548.png 2x" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/9/9841c1d93718dd442f9a22b7a6b5a82440f86548_2_10x10.png"></a></div><br>
אני משער שזה קורה בגלל שאני משתמש ב-set בפונקציה (על מנת למנוע כפילויות).<br>
מישהו יודע האם זאת הבעיה? ואם לא אז מה השגיאה אומרת?<p></p>
          <p><a href="https://forums.pythonic.guru/t/group-by/6842/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/group-by/6842/1</link>
        <pubDate>Sun, 31 May 2020 12:14:21 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6842-1</guid>
        <source url="https://forums.pythonic.guru/t/group-by/6842.rss">Group_by- בדיקות אוטומטיות</source>
      </item>
  </channel>
</rss>
