<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>שבוע 3 - בעיה בהעלאה חוזרת של תרגילים</title>
    <link>https://forums.pythonic.guru/t/topic/4843</link>
    <description>היי, 
אני לא מצליחה להעלות מחדש את תרגיל 41

הנה סדר הפעולות: 

1. העלאתי כבר את תרגיל 41 (ממש קולץ בישבן) שנמצא במחברת 1 והכל טוב ויפה
2. **בטעות דרסתי אותו** כשהעלאתי את מחברת 2 וקראתי לתרגיל 43 בטעות תרגיל 41.
עכשיו מתחיל הבעיות: 
3. כשניסיתי להעלאות שוב את מחברת 1 לא הצלחתי, תרגיל 41 נשאר אם הטקסט של תרגיל 43.
4. הייתי מתוחכמת: בפסקה של תרגיל 43 במחברת 2, עשיתי copy-paste לתרגיל 41 והעלאתי את מחברת 2 - זה עבד! 
**אבל!** נשתרבב לטקסט ב copy-paste עוד סוגר נוסף בסוף התרגיל שדופק את כל ההרצה.
5. נסיתי להעלות שוב את מחברת 1, את מחברת 2, מחברת חדשה אם תרגיל 41 - כלום לא עוזר.

בהיסטוריה של התרגיל אתם יכולים לראות שההעלאה הראשונה היא הנכונה.

בדקתי שאני כותבת תמיד # Upload 41 לפני התרגיל (בצורה הנכונה, זה הופך לי את זה כאן), הסיומת של המחברת היא .ipynb, עשיתי save.

לא יודעת מה הבעיה, אבל כרגע אני לא יכולה להעלות מחדש 
מאוד מתסכל</description>
    <language>he</language>
    <lastBuildDate>Thu, 16 Apr 2020 16:07:26 +0000</lastBuildDate>
    <category>מחוץ לקטגוריה</category>
    <atom:link href="https://forums.pythonic.guru/t/topic/4843.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>שבוע 3 - בעיה בהעלאה חוזרת של תרגילים</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>היי!<br>
נתקלת בטעות במערכת שלנו למניעת העלאה כפולה של תרגילים זהים, ולמרות שבד"כ היא עוזרת לחונכים ולחניכים, אצלך היא קצת מפריעה.<br>
הוסיפי כשורה אחרונה לתרגיל: <code># Reupload</code>.<br>
בהצלחה <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/topic/4843/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/4843/2</link>
        <pubDate>Thu, 16 Apr 2020 16:07:26 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-4843-2</guid>
        <source url="https://forums.pythonic.guru/t/topic/4843.rss">שבוע 3 - בעיה בהעלאה חוזרת של תרגילים</source>
      </item>
      <item>
        <title>שבוע 3 - בעיה בהעלאה חוזרת של תרגילים</title>
        <dc:creator><![CDATA[yael.maritz]]></dc:creator>
        <description><![CDATA[
            <p>היי,<br>
אני לא מצליחה להעלות מחדש את תרגיל 41</p>
<p>הנה סדר הפעולות:</p>
<ol>
<li>העלאתי כבר את תרגיל 41 (ממש קולץ בישבן) שנמצא במחברת 1 והכל טוב ויפה</li>
<li>
<strong>בטעות דרסתי אותו</strong> כשהעלאתי את מחברת 2 וקראתי לתרגיל 43 בטעות תרגיל 41.<br>
עכשיו מתחיל הבעיות:</li>
<li>כשניסיתי להעלאות שוב את מחברת 1 לא הצלחתי, תרגיל 41 נשאר אם הטקסט של תרגיל 43.</li>
<li>הייתי מתוחכמת: בפסקה של תרגיל 43 במחברת 2, עשיתי copy-paste לתרגיל 41 והעלאתי את מחברת 2 - זה עבד!<br>
<strong>אבל!</strong> נשתרבב לטקסט ב copy-paste עוד סוגר נוסף בסוף התרגיל שדופק את כל ההרצה.</li>
<li>נסיתי להעלות שוב את מחברת 1, את מחברת 2, מחברת חדשה אם תרגיל 41 - כלום לא עוזר.</li>
</ol>
<p>בהיסטוריה של התרגיל אתם יכולים לראות שההעלאה הראשונה היא הנכונה.</p>
<p>בדקתי שאני כותבת תמיד # Upload 41 לפני התרגיל (בצורה הנכונה, זה הופך לי את זה כאן), הסיומת של המחברת היא .ipynb, עשיתי save.</p>
<p>לא יודעת מה הבעיה, אבל כרגע אני לא יכולה להעלות מחדש<br>
מאוד מתסכל</p>
          <p><a href="https://forums.pythonic.guru/t/topic/4843/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/4843/1</link>
        <pubDate>Thu, 16 Apr 2020 14:16:47 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-4843-1</guid>
        <source url="https://forums.pythonic.guru/t/topic/4843.rss">שבוע 3 - בעיה בהעלאה חוזרת של תרגילים</source>
      </item>
  </channel>
</rss>
