<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>אליבי לרוצחים - שגיאה לא מובנת</title>
    <link>https://forums.pythonic.guru/t/topic/5852</link>
    <description>היי,
במהלך הפתרון נתקלתי בשגיאה הבאה:

&gt; TypeError: print_suspect() got an unexpected keyword argument &#39;name&#39;

זאת לאחר שניסיתי לעשות את הדבר הזה:

&gt; def check_suspects(suspects):
&gt;     for suspect in suspects:
&gt;         print(suspect)
&gt;         print_suspect(**suspect)

ניסיתי לגגל את השגיאה אבל לא מצאתי משהו שיועיל לי.

אשמח לעזרה, תודה!</description>
    <language>he</language>
    <lastBuildDate>Mon, 04 May 2020 15:55:24 +0000</lastBuildDate>
    <category>שבוע 4</category>
    <atom:link href="https://forums.pythonic.guru/t/topic/5852.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>אליבי לרוצחים - שגיאה לא מובנת</title>
        <dc:creator><![CDATA[elador9]]></dc:creator>
        <description><![CDATA[
            <p>לפי השגיאה - הפונקציה שלך מקבלת ארגומנט שהיא לא מצפה לו (name).<br>
ההסבר לכך כתוב באותה מחברת של התרגיל בנושא של ההתעסקות עם מילון, תנסה לחפש.</p>

אם אתה לא מוצא, אז תקרא: <a href="https://forums.pythonic.guru/t/topic/5852/2">(לחיצה לפרטים נוספים)</a>
<p>מקווה שזה עוזר <img src="https://forums.pythonic.guru/images/emoji/twitter/slight_smile.png?v=9" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/topic/5852/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/5852/2</link>
        <pubDate>Mon, 04 May 2020 15:55:24 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-5852-2</guid>
        <source url="https://forums.pythonic.guru/t/topic/5852.rss">אליבי לרוצחים - שגיאה לא מובנת</source>
      </item>
      <item>
        <title>אליבי לרוצחים - שגיאה לא מובנת</title>
        <dc:creator><![CDATA[assaf]]></dc:creator>
        <description><![CDATA[
            <p>היי,<br>
במהלך הפתרון נתקלתי בשגיאה הבאה:</p>
<blockquote>
<p>TypeError: print_suspect() got an unexpected keyword argument ‘name’</p>
</blockquote>
<p>זאת לאחר שניסיתי לעשות את הדבר הזה:</p>
<blockquote>
<p>def check_suspects(suspects):<br>
for suspect in suspects:<br>
print(suspect)<br>
print_suspect(**suspect)</p>
</blockquote>
<p>ניסיתי לגגל את השגיאה אבל לא מצאתי משהו שיועיל לי.</p>
<p>אשמח לעזרה, תודה!</p>
          <p><a href="https://forums.pythonic.guru/t/topic/5852/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/5852/1</link>
        <pubDate>Mon, 04 May 2020 15:30:41 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-5852-1</guid>
        <source url="https://forums.pythonic.guru/t/topic/5852.rss">אליבי לרוצחים - שגיאה לא מובנת</source>
      </item>
  </channel>
</rss>
