<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>יצירת חריגה - שאלת הבנה</title>
    <link>https://forums.pythonic.guru/t/topic/7618</link>
    <description>במחברת 4 בסעיף על יצירת חריגות:

כותבים חריגה שיורשת מ-Exception:
```
class AddressUnknownError(Exception):
    pass
```
ובקוד אחר כך &quot;תופסים&quot; שגיאת KeyError ומעלים את החריגה שיצרנו.

לא הבנתי למה זה לא טוב שהחריגה שיצרנו תירש מ-KeyError אם בכל מקרה מעלים אותה אחרי תפיסת שגיאת KeyError.

ניסיתי לשחק עם זה אבל יצא משהו שלא הבנתי. שיניתי את הקוד כך שהחריגה כן תירש מ-KeyError  ותדפיס משהו, ואת הקוד שאחרי שיניתי כך שרק תודפס השגיאה שנתפסה. אבל לא הודפס מה שכתבתי.
אשמח להסבר אני קצת מבולבל :sweat_smile:</description>
    <language>he</language>
    <lastBuildDate>Thu, 23 Jul 2020 08:15:00 +0000</lastBuildDate>
    <category>שבוע 8</category>
    <atom:link href="https://forums.pythonic.guru/t/topic/7618.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>יצירת חריגה - שאלת הבנה</title>
        <dc:creator><![CDATA[ori81510]]></dc:creator>
        <description><![CDATA[
            <p>ביצירת חריגה על כתובת לא ידועה נרצה לתפוס בדיוק את זה, ולא דברים לא קשורים כמו KeyError. ממה שהבנתי (ואני זוכר) מאותו הסבר - נכתב שצריך להזהר כאשר משתמשים בירושה ולשים לב להיות ספציפיים כדי שלא נתפוס גם דברים שאינם קשורים.</p>
<p>כדאי לשים לב לכלל האצבע: A יכול לרשת מ B אם A הוא סוג של B. למשל Dog יכול לרשת מ Animal. כך גם לגבי חריגות.</p>
          <p><a href="https://forums.pythonic.guru/t/topic/7618/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7618/2</link>
        <pubDate>Thu, 23 Jul 2020 08:05:59 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7618-2</guid>
        <source url="https://forums.pythonic.guru/t/topic/7618.rss">יצירת חריגה - שאלת הבנה</source>
      </item>
      <item>
        <title>יצירת חריגה - שאלת הבנה</title>
        <dc:creator><![CDATA[Alon.B.A]]></dc:creator>
        <description><![CDATA[
            <p>במחברת 4 בסעיף על יצירת חריגות:</p>
<p>כותבים חריגה שיורשת מ-Exception:</p>
<pre><code class="lang-auto">class AddressUnknownError(Exception):
    pass
</code></pre>
<p>ובקוד אחר כך “תופסים” שגיאת KeyError ומעלים את החריגה שיצרנו.</p>
<p>לא הבנתי למה זה לא טוב שהחריגה שיצרנו תירש מ-KeyError אם בכל מקרה מעלים אותה אחרי תפיסת שגיאת KeyError.</p>
<p>ניסיתי לשחק עם זה אבל יצא משהו שלא הבנתי. שיניתי את הקוד כך שהחריגה כן תירש מ-KeyError  ותדפיס משהו, ואת הקוד שאחרי שיניתי כך שרק תודפס השגיאה שנתפסה. אבל לא הודפס מה שכתבתי.<br>
אשמח להסבר אני קצת מבולבל <img src="https://forums.pythonic.guru/images/emoji/twitter/sweat_smile.png?v=9" title=":sweat_smile:" class="emoji" alt=":sweat_smile:"></p>
          <p><a href="https://forums.pythonic.guru/t/topic/7618/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/7618/1</link>
        <pubDate>Thu, 23 Jul 2020 07:22:29 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-7618-1</guid>
        <source url="https://forums.pythonic.guru/t/topic/7618.rss">יצירת חריגה - שאלת הבנה</source>
      </item>
  </channel>
</rss>
