<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>לא מצליח להתחבר לדאטה בייס</title>
    <link>https://forums.pythonic.guru/t/topic/8546</link>
    <description>אני לא יודע בדיוק מה קרה כאן הצלחתי להעלות לheroku ויצא בסדר. הבעיה היא שעכשיו כשאני מנסה להמשיך ולהוסיף דברים פתאום אני לא מצליח יותר לעבוד עם הדאטה בייס, כשאני עושה flask run אני מקבל את ההערה הזאת:
raise InterfaceError(&#39;Error, database must be initialized &#39;
peewee.InterfaceError: Error, database must be initialized before opening a connection.

ניסיתי אפילו לחזור לדוגמת הקוד הישנה יותר שבgithub ועדיין הוא מבחינתו לא נותן לי להתחבר. מישהו נתקל בזה אולי?</description>
    <language>he</language>
    <lastBuildDate>Thu, 10 Dec 2020 21:51:29 +0000</lastBuildDate>
    <category>שבוע 14</category>
    <atom:link href="https://forums.pythonic.guru/t/topic/8546.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>לא מצליח להתחבר לדאטה בייס</title>
        <dc:creator><![CDATA[pollakamir34]]></dc:creator>
        <description><![CDATA[
            <p>לא מאמין. שעה אני שובר על זה את הראש ואז עושה ריסטרט והתקלה נפתרה.</p>
          <p><a href="https://forums.pythonic.guru/t/topic/8546/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/8546/3</link>
        <pubDate>Thu, 10 Dec 2020 21:51:29 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8546-3</guid>
        <source url="https://forums.pythonic.guru/t/topic/8546.rss">לא מצליח להתחבר לדאטה בייס</source>
      </item>
      <item>
        <title>לא מצליח להתחבר לדאטה בייס</title>
        <dc:creator><![CDATA[Yam]]></dc:creator>
        <description><![CDATA[
            <p>יש מצב שהארוקו שינה את פרטי ההתחברות למסד הנתונים שלך?</p>
          <p><a href="https://forums.pythonic.guru/t/topic/8546/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/8546/2</link>
        <pubDate>Thu, 10 Dec 2020 21:43:00 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8546-2</guid>
        <source url="https://forums.pythonic.guru/t/topic/8546.rss">לא מצליח להתחבר לדאטה בייס</source>
      </item>
      <item>
        <title>לא מצליח להתחבר לדאטה בייס</title>
        <dc:creator><![CDATA[pollakamir34]]></dc:creator>
        <description><![CDATA[
            <p>אני לא יודע בדיוק מה קרה כאן הצלחתי להעלות לheroku ויצא בסדר. הבעיה היא שעכשיו כשאני מנסה להמשיך ולהוסיף דברים פתאום אני לא מצליח יותר לעבוד עם הדאטה בייס, כשאני עושה flask run אני מקבל את ההערה הזאת:<br>
raise InterfaceError('Error, database must be initialized ’<br>
peewee.InterfaceError: Error, database must be initialized before opening a connection.</p>
<p>ניסיתי אפילו לחזור לדוגמת הקוד הישנה יותר שבgithub ועדיין הוא מבחינתו לא נותן לי להתחבר. מישהו נתקל בזה אולי?</p>
          <p><a href="https://forums.pythonic.guru/t/topic/8546/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/topic/8546/1</link>
        <pubDate>Thu, 10 Dec 2020 21:17:57 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8546-1</guid>
        <source url="https://forums.pythonic.guru/t/topic/8546.rss">לא מצליח להתחבר לדאטה בייס</source>
      </item>
  </channel>
</rss>
