<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>שגיאה pytest - חיבור pewee</title>
    <link>https://forums.pythonic.guru/t/pytest-pewee/8609</link>
    <description>היי, 

עשיתי יוזר קבוץ conftest.py  ובקובץ בדיקה קראתי לו 
כמו בהסבר של ים בסרטון. 

כאשר אני מריץ אץ הבדיקה היא חוזרת לי עם  Error  בפונקציה הזו
![image|690x27](upload://xPoE19Cw9CJF95fiKWAsrJyof3H.png) 

טוען שהחיבור כבר פתוח. 
ממה שחיפשתי בגוגל כולם אומרים להכניס את הפונקציות הנ&quot;ל: 
http://docs.peewee-orm.com/en/latest/peewee/database.html#flask

שכבר קיימות אצלי בקוד.

האם מישהו נתקל במשהו דומה ויודע איך להתגבר ? 
ברכת הבודק האוטומטי לכל העזורים.</description>
    <language>he</language>
    <lastBuildDate>Mon, 04 Jan 2021 12:47:15 +0000</lastBuildDate>
    <category>מחוץ לקטגוריה</category>
    <atom:link href="https://forums.pythonic.guru/t/pytest-pewee/8609.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>שגיאה pytest - חיבור pewee</title>
        <dc:creator><![CDATA[aviadamar]]></dc:creator>
        <description><![CDATA[
            <p>כן זה יוצא זהה ובכל מקרה פותר את הבעיה בשני המקרים (: תודה</p>
          <p><a href="https://forums.pythonic.guru/t/pytest-pewee/8609/4">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest-pewee/8609/4</link>
        <pubDate>Mon, 04 Jan 2021 12:47:15 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8609-4</guid>
        <source url="https://forums.pythonic.guru/t/pytest-pewee/8609.rss">שגיאה pytest - חיבור pewee</source>
      </item>
      <item>
        <title>שגיאה pytest - חיבור pewee</title>
        <dc:creator><![CDATA[gALz]]></dc:creator>
        <description><![CDATA[
            <p>מממ אני פשוט בקונקט הוספתי בדיקה אם החיבור סגור<br>
<code>     if database.is_closed(): </code></p>
<p>נראה לי אבל זהה?</p>
          <p><a href="https://forums.pythonic.guru/t/pytest-pewee/8609/3">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest-pewee/8609/3</link>
        <pubDate>Mon, 04 Jan 2021 11:23:39 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8609-3</guid>
        <source url="https://forums.pythonic.guru/t/pytest-pewee/8609.rss">שגיאה pytest - חיבור pewee</source>
      </item>
      <item>
        <title>שגיאה pytest - חיבור pewee</title>
        <dc:creator><![CDATA[aviadamar]]></dc:creator>
        <description><![CDATA[
            <p>כנראה שהחיבור נשאר פתוח ולכן יש לעשות ווידאו שהוא סגור על ידי הוספת הפונקציה close()<br>
לפני שמבצעים חיבור.</p>
<p>פתרון: <a href="https://teamtreehouse.com/community/tests-failing-and-i-cant-figure-out-why-getting-peeweeoperationalerror-connection-already-open-please-help" class="inline-onebox">Tests failing and I can't figure out why. Getting "peewee.OperationalError: Connection already open" Please help! | Treehouse Community</a></p>
          <p><a href="https://forums.pythonic.guru/t/pytest-pewee/8609/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest-pewee/8609/2</link>
        <pubDate>Sun, 03 Jan 2021 17:33:09 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8609-2</guid>
        <source url="https://forums.pythonic.guru/t/pytest-pewee/8609.rss">שגיאה pytest - חיבור pewee</source>
      </item>
      <item>
        <title>שגיאה pytest - חיבור pewee</title>
        <dc:creator><![CDATA[aviadamar]]></dc:creator>
        <description><![CDATA[
            <p>היי,</p>
<p>עשיתי יוזר קבוץ conftest.py  ובקובץ בדיקה קראתי לו<br>
כמו בהסבר של ים בסרטון.</p>
<p>כאשר אני מריץ אץ הבדיקה היא חוזרת לי עם  Error  בפונקציה הזו<br>
</p><div class="lightbox-wrapper"><a class="lightbox" href="https://forums.pythonic.guru/uploads/default/original/2X/e/ed1718d10c9927afeacebd4ace39085bb2fe2aa1.png" data-download-href="https://forums.pythonic.guru/uploads/default/ed1718d10c9927afeacebd4ace39085bb2fe2aa1" title="image"><img src="https://forums.pythonic.guru/uploads/default/original/2X/e/ed1718d10c9927afeacebd4ace39085bb2fe2aa1.png" alt="image" data-base62-sha1="xPoE19Cw9CJF95fiKWAsrJyof3H" width="690" height="27" data-small-upload="https://forums.pythonic.guru/uploads/default/optimized/2X/e/ed1718d10c9927afeacebd4ace39085bb2fe2aa1_2_10x10.png"></a></div><p></p>
<p>טוען שהחיבור כבר פתוח.<br>
ממה שחיפשתי בגוגל כולם אומרים להכניס את הפונקציות הנ"ל:<br>
<a href="http://docs.peewee-orm.com/en/latest/peewee/database.html#flask" class="onebox" target="_blank" rel="noopener">http://docs.peewee-orm.com/en/latest/peewee/database.html#flask</a></p>
<p>שכבר קיימות אצלי בקוד.</p>
<p>האם מישהו נתקל במשהו דומה ויודע איך להתגבר ?<br>
ברכת הבודק האוטומטי לכל העזורים.</p>
          <p><a href="https://forums.pythonic.guru/t/pytest-pewee/8609/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/pytest-pewee/8609/1</link>
        <pubDate>Sun, 03 Jan 2021 17:12:58 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-8609-1</guid>
        <source url="https://forums.pythonic.guru/t/pytest-pewee/8609.rss">שגיאה pytest - חיבור pewee</source>
      </item>
  </channel>
</rss>
