<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>תקלה מוזרה במחברת ראשונה - sets</title>
    <link>https://forums.pythonic.guru/t/sets/6507</link>
    <description>הי,

נתקלתי בבאג שלא ברור לי ממש בתחילת המחברת. כשאני מנסה להריץ את אותו הקוד בPycharm אין שום בעיה.

לדוגמה, כשאני מנסה להריץ את הקוד הבא:

&#39;&#39;&#39;
alphabet = [ ]
for char in range(ord(&quot;A&quot;), ord(&quot;z&quot;)):
    if chr(char).isalpha():
        alphabet.append(chr(char))

test = set(alphabet)
print(test)
&#39;&#39;&#39;

אני מקבל את הerror הבא:

TypeError: &#39;dict&#39; object is not callable

זה קורה בכל פעם שאני מנסה ליצור סט מתוך רשימה (לא כשאני מנסה ליצור סט עם סוגריים מסולסלים).</description>
    <language>he</language>
    <lastBuildDate>Sat, 23 May 2020 20:06:26 +0000</lastBuildDate>
    <category>שבוע 6</category>
    <atom:link href="https://forums.pythonic.guru/t/sets/6507.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>תקלה מוזרה במחברת ראשונה - sets</title>
        <dc:creator><![CDATA[orpazf]]></dc:creator>
        <description><![CDATA[
            <p>ככל הנראה אחד מהפונקציות נדרסה בתא קודם ע"י מילון, כלומר שהיה משפט כמו למשל <code>set = {}</code>. נס  לעשות restart kernek ולהריץ שוב את התא</p>
          <p><a href="https://forums.pythonic.guru/t/sets/6507/2">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/sets/6507/2</link>
        <pubDate>Sat, 23 May 2020 20:06:26 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6507-2</guid>
        <source url="https://forums.pythonic.guru/t/sets/6507.rss">תקלה מוזרה במחברת ראשונה - sets</source>
      </item>
      <item>
        <title>תקלה מוזרה במחברת ראשונה - sets</title>
        <dc:creator><![CDATA[yaromguy]]></dc:creator>
        <description><![CDATA[
            <p>הי,</p>
<p>נתקלתי בבאג שלא ברור לי ממש בתחילת המחברת. כשאני מנסה להריץ את אותו הקוד בPycharm אין שום בעיה.</p>
<p>לדוגמה, כשאני מנסה להריץ את הקוד הבא:</p>
<p>‘’’<br>
alphabet = <span class="chcklst-box fa fa-square-o fa-fw"></span><br>
for char in range(ord(“A”), ord(“z”)):<br>
if chr(char).isalpha():<br>
alphabet.append(chr(char))</p>
<p>test = set(alphabet)<br>
print(test)<br>
‘’’</p>
<p>אני מקבל את הerror הבא:</p>
<p>TypeError: ‘dict’ object is not callable</p>
<p>זה קורה בכל פעם שאני מנסה ליצור סט מתוך רשימה (לא כשאני מנסה ליצור סט עם סוגריים מסולסלים).</p>
          <p><a href="https://forums.pythonic.guru/t/sets/6507/1">קריאת הנושא במלואו</a></p>
        ]]></description>
        <link>https://forums.pythonic.guru/t/sets/6507/1</link>
        <pubDate>Sat, 23 May 2020 20:03:14 +0000</pubDate>
        <guid isPermaLink="false">forums.pythonic.guru-post-6507-1</guid>
        <source url="https://forums.pythonic.guru/t/sets/6507.rss">תקלה מוזרה במחברת ראשונה - sets</source>
      </item>
  </channel>
</rss>
